# Contextual based neural lemmatization with Flair

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pip install --upgrade pip
!pip install --upgrade flair

In [ ]:
from flair.data import Corpus
from flair.datasets import ColumnCorpus
from flair.embeddings import TokenEmbeddings, WordEmbeddings, StackedEmbeddings, FlairEmbeddings, CharacterEmbeddings
from typing import List

# ASSIGNMENT 1

Please inspect the data we provided (train, dev and test sets available): 'content/drive/My Drive/Colab Notebooks/2022-ILTAPP/datasets/sigmorphon2019/'

+ TODO Try to spot the differences with the Lab 04-ner-training-tagging_TODO.ipynb.
+ TODO: define the columns required to instantiate the ColumnCorpus and the tag we want to predict.
+ TODO: use downsampling to speed up training.
+ TODO: print the total number of tags to predict in the corpus and check how this changes as you change the downsampling.
+ TODO: experiment with Classic Embeddings, CharacterEmbeddings and Flair Embeddings for improving accuracy performance (also with number of epochs).
  + HINT: Do not combine more than two types of embeddings to avoid running out RAM.

In [ ]:
# TODO define columns

columns = {0: 'text', 1:'pos', 2: 'lemma_pattern'}

# this is the folder in which train, test and dev files reside
data_folder = '/content/drive/MyDrive/2022-ILTAPP/datasets/sigmorphon2019'



# TODO get the corpus

# init a corpus using column format, data folder and the names of the train, dev and test files
corpus: Corpus = ColumnCorpus(data_folder, columns,
                              train_file='en-ewt-ud-ses-true-train.tsv',
                              test_file='en-ewt-ud-ses-true-test.tsv',
                              dev_file='en-ewt-ud-ses-true-dev.tsv')




2022-03-15 15:10:08,309 Reading data from /content/drive/MyDrive/2022-ILTAPP/datasets/sigmorphon2019
2022-03-15 15:10:08,311 Train: /content/drive/MyDrive/2022-ILTAPP/datasets/sigmorphon2019/en-ewt-ud-ses-true-train.tsv
2022-03-15 15:10:08,316 Dev: /content/drive/MyDrive/2022-ILTAPP/datasets/sigmorphon2019/en-ewt-ud-ses-true-dev.tsv
2022-03-15 15:10:08,318 Test: /content/drive/MyDrive/2022-ILTAPP/datasets/sigmorphon2019/en-ewt-ud-ses-true-test.tsv


In [ ]:
# 2. what tag do we want to predict?
tag_type = 'lemma_pattern'

# 3. make the tag dictionary from the corpus
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)

# TODO print total number of tags
print(tag_dictionary.idx2item)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated method make_tag_dictionary. (Use 'make_label_dictionary' instead.) -- Deprecated since version 0.8.
  """


[b'O', b'\xe2\x86\x930;d\xc2\xa6+', b'\xe2\x86\x930;d--+b\xc2\xa6+', b'\xe2\x86\x930;d\xc2\xa6-+', b'\xe2\x86\x910\xc2\xa6\xe2\x86\x931;d\xc2\xa6+', b'\xe2\x86\x930;d\xc2\xa6--+', b'\xe2\x86\x930;d\xc2\xa6---+e+', b'\xe2\x86\x930;d\xc2\xa6---+', b'\xe2\x86\x930;abe', b'\xe2\x86\x930;d\xc2\xa6+e\xe2\x86\x92-+', b'\xe2\x86\x930;d\xc2\xa6-+d+', b'\xe2\x86\x910\xc2\xa6\xe2\x86\x93-1;d\xc2\xa6+', b'\xe2\x86\x910\xc2\xa6\xe2\x86\x931;ai', b'\xe2\x86\x930;d-+w+i\xc2\xa6+', b'\xe2\x86\x930;d\xc2\xa6--+e+', b'\xe2\x86\x930;d\xc2\xa6-\xe2\x86\x92--+e+', b'\xe2\x86\x930;d-+h+a\xc2\xa6+', b'\xe2\x86\x930;d-+w+o+u+l\xc2\xa6+', b'\xe2\x86\x930;d\xc2\xa6-+v+e+', b'\xe2\x86\x930;d\xc2\xa6----+', b'\xe2\x86\x930;d\xc2\xa6-----+i+n+k+', b'\xe2\x86\x930;ago', b'\xe2\x86\x930;d\xc2\xa6--+y+', b'\xe2\x86\x930;d+s\xc2\xa6-+', b'\xe2\x86\x930;d\xe2\x86\x92-+i\xc2\xa6+', b'\xe2\x86\x930;d\xc2\xa6-+o\xe2\x86\x92+', b'\xe2\x86\x930;d\xc2\xa6--+a\xe2\x86\x92+e+', b'\xe2\x86\x930;a"', b"\xe2\x86\x930;a''", b'\xe2

In [ ]:
# TODO play with embeddings and check performance; which one is the best combination?
embedding_types: List[TokenEmbeddings] = [
      CharacterEmbeddings(),
      WordEmbeddings('glove'),
      FlairEmbeddings('en-forward', chars_per_chunk=128),
      FlairEmbeddings('en-backward', chars_per_chunk=128),
      ]

embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)


2022-03-15 15:10:22,835 https://flair.informatik.hu-berlin.de/resources/characters/common_characters not found in cache, downloading to /tmp/tmpxd01ap24


100%|██████████| 2887/2887 [00:00<00:00, 771664.27B/s]

2022-03-15 15:10:22,959 copying /tmp/tmpxd01ap24 to cache at /root/.flair/datasets/common_characters
2022-03-15 15:10:22,962 removing temp file /tmp/tmpxd01ap24


2022-03-15 15:10:33,218 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim.vectors.npy not found in cache, downloading to /tmp/tmp6ztd5ywb


100%|██████████| 160000128/160000128 [00:04<00:00, 37112421.09B/s]

2022-03-15 15:10:37,633 copying /tmp/tmp6ztd5ywb to cache at /root/.flair/embeddings/glove.gensim.vectors.npy


2022-03-15 15:10:37,964 removing temp file /tmp/tmp6ztd5ywb
2022-03-15 15:10:38,081 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim not found in cache, downloading to /tmp/tmpppoiqu9v


100%|██████████| 21494764/21494764 [00:00<00:00, 30837916.70B/s]


2022-03-15 15:10:38,912 copying /tmp/tmpppoiqu9v to cache at /root/.flair/embeddings/glove.gensim
2022-03-15 15:10:38,960 removing temp file /tmp/tmpppoiqu9v
2022-03-15 15:10:41,373 https://flair.informatik.hu-berlin.de/resources/embeddings/flair/news-forward-0.4.1.pt not found in cache, downloading to /tmp/tmpqrl__eiw


100%|██████████| 73034624/73034624 [00:02<00:00, 35853073.81B/s]

2022-03-15 15:10:43,505 copying /tmp/tmpqrl__eiw to cache at /root/.flair/embeddings/news-forward-0.4.1.pt


2022-03-15 15:10:43,661 removing temp file /tmp/tmpqrl__eiw
2022-03-15 15:10:44,115 https://flair.informatik.hu-berlin.de/resources/embeddings/flair/news-backward-0.4.1.pt not found in cache, downloading to /tmp/tmp11bldepy


100%|██████████| 73034575/73034575 [00:02<00:00, 34482949.18B/s]

2022-03-15 15:10:46,334 copying /tmp/tmp11bldepy to cache at /root/.flair/embeddings/news-backward-0.4.1.pt


2022-03-15 15:10:46,479 removing temp file /tmp/tmp11bldepy


In [ ]:
# initialize sequence tagger
from flair.models import SequenceTagger

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type
)

In [ ]:
# initialize trainer
from flair.trainers import ModelTrainer
trainer: ModelTrainer = ModelTrainer(tagger, corpus)

In [ ]:
trainer.train('/content/drive/MyDrive/2022-ILTAPP/glove-lemma-model', 
              mini_batch_size=16, 
              train_with_dev=False, 
              max_epochs=5,
              patience=0)

# ASSIGNMENT 2

In this assignment we will be using the trained model in the previous step to tag some texts.

**NOTE**: If you use the Basque corpus, you can get a document to process in Basque from a newspaper: https://www.berria.eus/

+ TODO: Pick a document of your choice and run the following Flair components:
  + Tokenize and segment the document into sentences.
  + Instiantiate a SequenceTagger with the generated lemmatizer model.
  + Lemmatize the sentences and print the results (ideally saving the predictions into a list of Sentence objects).

In [ ]:
# TODO add your code here

from flair.models import SequenceTagger
from flair.tokenization import SegtokSentenceSplitter

# TODO add your code here
tagger = SequenceTagger.load('/content/drive/MyDrive/2022-ILTAPP/glove-lemma-model/final-model.pt')

sample_text = open('/content/drive/My Drive/2022-ILTAPP/datasets/sample_text.txt', 'r').read()

# initialize sentence splitter
splitter = SegtokSentenceSplitter()
# use splitter to split text into list of sentences
sentences = splitter.split(sample_text)
#data = Sentence(text_to_tag, use_tokenizer=True)
tagger.predict(sentences)
for sentence in sentences:
    print(sentence.to_tagged_string())

2022-03-15 15:38:00,665 loading file /content/drive/MyDrive/2022-ILTAPP/es-lemma-model/final-model.pt
KYIV <↑0¦↓-1;d¦+> , <↓0;d¦+> Ukraine <↑0¦↓1;d¦+> — <↓0;d¦+> Ukraine <↑0¦↓1;d¦+> ’s <↓0;d-+'¦+> President <↑0¦↓1;d¦+> Volodymyr <↑0¦↓1;d¦+> Zelenskyy <↑0¦↓1;d¦+> says <↓0;d¦-+> that <↓0;d¦+> talks <↓0;d¦-+> between <↓0;d¦+> Ukrainian <↓0;d¦+> and <↓0;d¦+> Russian <↓0;d¦+> delegations <↓0;d¦-+> will <↓0;d¦+> continue <↓0;d¦+> Tuesday <↑0¦↓1;d¦+> . <↓0;d¦+>
Speaking <↓0;d¦---+> in <↓0;d¦+> a <↓0;d¦+> video <↓0;d¦+> address <↓0;d¦+> , <↓0;d¦+> Zelenskyy <↑0¦↓1;d¦+> said <↓0;d¦--+y+> that <↓0;d¦+> the <↓0;d¦+> Ukrainian <↓0;d¦+> delegation <↓0;d¦+> did <↓0;d¦--+o+> good <↓0;d¦+> work <↓0;d¦+> during <↓0;d¦+> Monday <↑0¦↓1;d¦+> ’s <↓0;d-+'¦+> talks <↓0;d¦-+> . <↓0;d¦+>
He <↓0;d¦+> did <↓0;d¦--+o+> n’t <↓0;d¦-+o→+> provide <↓0;d¦+> further <↓0;d¦+> details <↓0;d¦-+> . <↓0;d¦+>
He <↓0;d¦+> said <↓0;d¦--+y+> he <↓0;d¦+> spoke <↓0;d¦--→+a+k+> Monday <↑0¦↓1;d¦+> to <↓0;d¦+> Israeli <↓0;d¦+> Prime

# ASSIGNMENT 3

As you can see in the previous step, the model we trained predicts this weird lemma_rules based on the minimum script edits generated by the get_ses_affixes.py script (in the resources folder). In order to obtain the real lemma we need to decode the lemma_rule using the function _apply_lemma_rule(form, lemma_rule) below.

+ This function takes as parameters the original word we want to lemmatize and the lemma_rule predicted by our lemmatizer model.

  ```
  decoded_lemma = _apply_lemma_rule('partidua', '↓0;d¦-+')
  print(decoded_lemma)
  'partidu'
  ```
Ideally you may have saved the previous predictions in a list of Sentence objects. Being that the case, you need to:

+ TODO: Iterate over the sentences to extract the lemma prediction (or lemma_rule) which will be used, together with the word, as input to obtain the decoded lemma.
+ TODO: print the results with the decoded lemma.
 

In [ ]:
def _apply_lemma_rule(form, lemma_rule):
    if ';' not in lemma_rule:
        raise ValueError('lemma_rule %r for form %r missing semicolon' % (lemma_rule, form))
    casing, rule = lemma_rule.split(";", 1)
    if rule.startswith("a"):
        lemma = rule[1:]
    else:
        form = form.lower()
        rules, rule_sources = rule[1:].split("¦"), []
        assert len(rules) == 2
        for rule in rules:
            source, i = 0, 0
            while i < len(rule):
                if rule[i] == "→" or rule[i] == "-":
                    source += 1
                else:
                    assert rule[i] == "+"
                    i += 1
                i += 1
            rule_sources.append(source)

        try:
            lemma, form_offset = "", 0
            for i in range(2):
                j, offset = 0, (0 if i == 0 else len(form) - rule_sources[1])
                while j < len(rules[i]):
                    if rules[i][j] == "→":
                        lemma += form[offset]
                        offset += 1
                    elif rules[i][j] == "-":
                        offset += 1
                    else:
                        assert (rules[i][j] == "+")
                        lemma += rules[i][j + 1]
                        j += 1
                    j += 1
                    # print(lemma)
                if i == 0:
                    lemma += form[rule_sources[0]: len(form) - rule_sources[1]]
        except:
            lemma = lemma

    for rule in casing.split("¦"):
        if rule == "↓0": continue  # The lemma is lowercased initially
        if not rule: continue  # Empty lemma might generate empty casing rule
        case, offset = rule[0], int(rule[1:])
        lemma = lemma[:offset] + (lemma[offset:].upper() if case == "↑" else lemma[offset:].lower())
    return lemma


In [ ]:
!pip install syntok

In [ ]:
# TODO add your code here
from flair.data import Sentence
from flair.models import SequenceTagger
from syntok.tokenizer import Tokenizer
import syntok.segmenter as segmenter


for sent in sentences:
  for lemma in sent.get_spans('lemma_pattern'):

    print(f" The lemma of {lemma.text} is --->  { _apply_lemma_rule(lemma.text, str(lemma.labels[0]).split('(')[0])}",)

#for sentence in sentences:
#   for token in sentence:
#      tag = str(token.get_tag('lemma'))
#      tag = tag.split()[0]
#      decoded_lemma = _apply_lemma_rule(token.text, tag)
#      print(f'{token} --> Lemma: {decoded_lemma}')

 The lemma of KYIV is --->  KYIV 
 The lemma of , is --->  , 
 The lemma of Ukraine is --->  Ukraine 
 The lemma of — is --->  — 
 The lemma of Ukraine is --->  Ukraine 
 The lemma of ’s is --->  's 
 The lemma of President is --->  President 
 The lemma of Volodymyr is --->  Volodymyr 
 The lemma of Zelenskyy is --->  Zelenskyy 
 The lemma of says is --->  say 
 The lemma of that is --->  that 
 The lemma of talks is --->  talk 
 The lemma of between is --->  between 
 The lemma of Ukrainian is --->  ukrainian 
 The lemma of and is --->  and 
 The lemma of Russian is --->  russian 
 The lemma of delegations is --->  delegation 
 The lemma of will is --->  will 
 The lemma of continue is --->  continue 
 The lemma of Tuesday is --->  Tuesday 
 The lemma of . is --->  . 
 The lemma of Speaking is --->  speak 
 The lemma of in is --->  in 
 The lemma of a is --->  a 
 The lemma of video is --->  video 
 The lemma of address is --->  address 
 The lemma of , is --->  , 
 The lemma of Zele

# BONUS ASSIGNMENT 4 

+ TODO Obtain manually the distance between two strings using the Levenshtein distance algorithm we presented in class for the following two words:

````
mellifluous -> mellow
````

You can write the matrix here using markdown.

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.7/55.7 KB 5.9 MB/s eta 0:00:00


In [3]:
import numpy as np

def levenshtein(seq1, seq2):
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros ((size_x, size_y))
    for x in range(size_x):
        matrix [x, 0] = x
    for y in range(size_y):
        matrix [0, y] = y

    for x in range(1, size_x):
        for y in range(1, size_y):
            if seq1[x-1] == seq2[y-1]:
                matrix [x,y] = min(
                    matrix[x-1, y] + 1,
                    matrix[x-1, y-1],
                    matrix[x, y-1] + 1
                )
            else:
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )
    print (matrix)
    return (matrix[size_x - 1, size_y - 1])
  
levenshtein("mellifluous", "mellow")


[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 1.  0.  1.  2.  3.  4.  5.]
 [ 2.  1.  0.  1.  2.  3.  4.]
 [ 3.  2.  1.  0.  1.  2.  3.]
 [ 4.  3.  2.  1.  0.  1.  2.]
 [ 5.  4.  3.  2.  1.  1.  2.]
 [ 6.  5.  4.  3.  2.  2.  2.]
 [ 7.  6.  5.  4.  3.  3.  3.]
 [ 8.  7.  6.  5.  4.  4.  4.]
 [ 9.  8.  7.  6.  5.  4.  5.]
 [10.  9.  8.  7.  6.  5.  5.]
 [11. 10.  9.  8.  7.  6.  6.]]


6.0